# day7

今天给框架加上错误处理机制，来处理框架的测试不完备or用户传来不正确的参数导致的错误。使得发生不重要的错误时，服务不会宕机，并在日志中打印错误信息。

# panic
代表程序发生了无法恢复的错误

## 通常造成panic的情况有：
* 数组越界
* 空指针引用
* 类型断言失败
* 除以 0
* 主动调用 panic()

## panic 时，会发生什么
* 停止当前函数
* 执行延迟调用 defer (多个defer按照压栈倒序执行)
* 如果当前函数没有处理 panic 则一直向上传递，直到传到 main 函数
* 仍未被处理则程序中止并打印错误信息

## 如何处理
使用recover()来补货 panic，recover只能在defer中使用

如果在defer中使用了recover()
* 且发生错误，则 recover 返回 panic的 值
* 没发生错误，recover 返回 nil


# defer

* defer 后的函数不会立即执行，而是压入栈中
* defer所在的函数返回时，会依次出栈执行
* 如遇panic，则会在panic后传导到当前函数并要中止前执行defer的栈

## 常见用途

* 资源清理
    * 确保文件使用完毕后关闭
    * 关闭数据库连接，确保数据库连接顺利关闭
    * 解锁互斥锁，确保互斥锁使用后顺利释放
* 错误处理
    * 发生错误的时候清理错误
    * panic时 recover()
* 日志
    * 函数结束时记录日志


# 今天要加的地方
一个错误处理的handler，默认放在Context实例的中间件的前列，这样只要在Context的生命周期中发生错误，都会defer recover然后捕获panic的err并打印，使得服务不会因为一个请求发生的错误而宕机。